### ISSUE TITLE
Feature Request: Option to create media links instead of raw text

### ISSUE THREAD

**Issue by DirkBloedorn** [johansan/obsidian-featured-image#1]
Current behavior:
The plugin generates frontmatter entries, such as:
feature: mythumb.png

Desired behavior:
Creation of media links, such as:
feature: ![[mythumb.png]]

Reason: In DataView it is possible to create media links from the text parameters, but it is more complex. In the DB Folder plugin, it is even more complicated or even impossible to display it as a thumbnail if it is not a media link.

I would therefore like to suggest creating media links as an option in the settings.

Thank you for your great plugin! It realy makes my workflow much easier.

**Comment by johansan** [comment]
Thanks for your positive feedback! 

I have already fixed this for version 1.0.5, but before I publish it I just want to make sure:

If I set the feature to ![[mythumb.png]] in Frontmatter, Obsidian will then write it to the file as:
---
feature: "![[mythumb.png]]"
---

Note the quotation marks. It does this if the frontmatter property includes markdown syntax. When reading the property however the quotations marks won't be included. Will this work for your use case?

**Comment by johansan** [comment]
I just published 1.0.5 - maybe you can try it out and report here how it works for your use case?

**Comment by johansan** [comment]
Closing it now, let me know if you need further changes! 👍

**Comment by DirkBloedorn** [comment]
Hi,
I have now tried 1.0.6 and it works wonderfully in my vault. Thank you very much!
