### ISSUE TITLE
Fails to fetch playstore thumbnails..

### ISSUE THREAD

**Issue by zuwf** [johansan/obsidian-featured-image#3]
Cards created by auto card link for playstore URLs contains a different image format and which has no extensions by default. 

I followed the URL via browser and tested adding extensions after that path to find what kind of image it is by default, but the links become broken when adding extensions..

On the other hand I checked saving the image displayed via browser it shows that was a png file.

I don't know how to fetch these images from cards.

**Comment by johansan** [comment]
Thanks I will look into that!

**Comment by johansan** [comment]
I have updated the external link detection code and it should work now, download the latest version and see if it works for you. Thanks for posting!
