### ISSUE TITLE
Option to disable automatic removal

### ISSUE THREAD

**Issue by caglarongan** [johansan/obsidian-featured-image#4]
Hello and thanks for this very necessary plugin !

I enabled "Only update if frontmatter property exists" because I don't want to use plugin vault-wide; but only in some files.
So I created a template with a null "cover" property, so i can add an image after I created the note.
After the note creation, when I add an image , the `cover` property doesn't get updated.

So I've tried adding a placeholder value as `cover: "![[coverimage.png]]"` to my template. But this time, the property is automatically removed because there isn't a `![[coverimage.png]]`present.

Can we please have the option to disable auto removal of the featured image property?

This is also necessary because, a user may delete and add another image to a note while note-making. And if the featured-image-property gets removed during that, a lot of manual work is needed again...

***
Alternatively, an option for "Included Folders" list can work. So a user can only adress a few selected folders rather than excluding a lot of folders/subfolders.

Thanks again for everything .

**Comment by johansan** [comment]
Hi, thanks for the positive feedback! I just published 1.1.4 it has a new setting "Keep empty property". 👍

**Comment by caglarongan** [comment]
Thank you for your quick reply and fix :)

Now it allows for an empty property  but it doesn't update the (empty)  property value when I add an image into the note.
The property value stays at `""` or just blank.

**Comment by caglarongan** [comment]
Here's a demo:

https://github.com/user-attachments/assets/69256a12-547d-4d1b-bab3-d32e69bc8c0b

**Comment by johansan** [comment]
Hi, I just published 1.1.5 it should fix this issue, thanks a lot for the video! 👍

**Comment by caglarongan** [comment]
Awesome, thank you 🍫
